//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.Accounts = new HashSet<Account>();
            this.ExaminationsPapers = new HashSet<ExaminationsPaper>();
            this.JoinsIns = new HashSet<JoinsIn>();
        }
    
        public int CandidateID { get; set; }
        public int AccountID { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<ExaminationsPaper> ExaminationsPapers { get; set; }
        public virtual ICollection<JoinsIn> JoinsIns { get; set; }
    }
}
