//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.SchedulesCars = new HashSet<SchedulesCar>();
        }
    
        public int CarID { get; set; }
        public int CharityExamID { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public string NumberPlate { get; set; }
        public int TotalSlots { get; set; }
        public int AvailableSlots { get; set; }
    
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual Sponsor Sponsor { get; set; }
        public virtual ICollection<SchedulesCar> SchedulesCars { get; set; }
    }
}
