//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int FundID { get; set; }
        public int SponsorID { get; set; }
        public int CharityExamID { get; set; }
        public double FundSponsored { get; set; }
        public bool IsOnlineFunding { get; set; }
    
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
