//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodge
    {
        public Lodge()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int LodgeID { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public int CharityExamID { get; set; }
        public int TotalRooms { get; set; }
        public int TotalSlots { get; set; }
        public int AvailableSlots { get; set; }
    
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual Sponsor Sponsor { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
