//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int ProfileID { get; set; }
        public int AccountID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public bool IsFemale { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Account Account { get; set; }
    }
}
