//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public Volunteer()
        {
            this.Accounts = new HashSet<Account>();
            this.SchedulesVolunteers = new HashSet<SchedulesVolunteer>();
        }
    
        public int VolunteerID { get; set; }
        public int AccountID { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<SchedulesVolunteer> SchedulesVolunteers { get; set; }
    }
}
