//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChairitiesExam
    {
        public ChairitiesExam()
        {
            this.Cars = new HashSet<Car>();
            this.ExaminationsPapers = new HashSet<ExaminationsPaper>();
            this.Funds = new HashSet<Fund>();
            this.Lodges = new HashSet<Lodge>();
            this.ParticipantVolunteers = new HashSet<ParticipantVolunteer>();
        }
    
        public int CharityExamID { get; set; }
        public int ExamID { get; set; }
        public int CharityID { get; set; }
        public int TotalSlotsLodges { get; set; }
        public int AvailableSlotsLodges { get; set; }
        public int TotalSlotsVehicles { get; set; }
        public int AvailableSlotsVehicles { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Charity Charity { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual ICollection<ExaminationsPaper> ExaminationsPapers { get; set; }
        public virtual ICollection<Fund> Funds { get; set; }
        public virtual ICollection<Lodge> Lodges { get; set; }
        public virtual ICollection<ParticipantVolunteer> ParticipantVolunteers { get; set; }
    }
}
