//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRequest
    {
        public int ID { get; set; }
        public int ActiveID { get; set; }
        public int ReceiveID { get; set; }
        public int GroupID { get; set; }
    
        public virtual ExaminationsPaper Active { get; set; }
        public virtual ExaminationsPaper Receive { get; set; }
        public virtual Group Group { get; set; }
    }
}
