//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public University()
        {
            this.UniversitiesExaminations = new HashSet<UniversitiesExamination>();
        }
    
        public int UniversityID { get; set; }
        public string Name { get; set; }
        public string UniversityCode { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<UniversitiesExamination> UniversitiesExaminations { get; set; }
    }
}
