//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Cars = new HashSet<Car>();
            this.ExaminationsPapers = new HashSet<ExaminationsPaper>();
        }
    
        public int VenueID { get; set; }
        public int UniExamID { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Address { get; set; }
        public bool IsRemovable { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<ExaminationsPaper> ExaminationsPapers { get; set; }
        public virtual UniversitiesExamination UniversitiesExamination { get; set; }
    }
}
