//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public Volunteer()
        {
            this.SchedulesVolunteers = new HashSet<SchedulesVolunteer>();
        }
    
        public int VolunteerID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> CharityExamID { get; set; }
        public string JobName { get; set; }
        public string Description { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual ICollection<SchedulesVolunteer> SchedulesVolunteers { get; set; }
    }
}
