//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsSchedulesCar
    {
        public int DetailScheduleCarID { get; set; }
        public int ScheduleCarID { get; set; }
        public System.DateTime Day { get; set; }
        public string PickUpTime { get; set; }
        public string ArriveTime { get; set; }
    
        public virtual SchedulesCar SchedulesCar { get; set; }
    }
}
