//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public Sponsor()
        {
            this.Cars = new HashSet<Car>();
            this.Funds = new HashSet<Fund>();
            this.Lodges = new HashSet<Lodge>();
        }
    
        public int SponsorID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<Fund> Funds { get; set; }
        public virtual ICollection<Lodge> Lodges { get; set; }
    }
}
