//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Articles = new HashSet<Article>();
            this.Candidates = new HashSet<Candidate>();
            this.Charities = new HashSet<Charity>();
            this.Profiles = new HashSet<Profile>();
            this.Sponsors = new HashSet<Sponsor>();
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public int AccountID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public int RoleID { get; set; }
        public string Code { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual ICollection<Charity> Charities { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Sponsor> Sponsors { get; set; }
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
