//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comments1 = new HashSet<Comment>();
        }
    
        public int CommentID { get; set; }
        public int ArticleID { get; set; }
        public int AccountID { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ReplyFor { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual Comment Comment1 { get; set; }
    }
}
