//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsScheduleExam
    {
        public int DetailsScheduleExamID { get; set; }
        public int ExamID { get; set; }
        public System.DateTime Day { get; set; }
        public System.DateTime BeginHour { get; set; }
        public System.DateTime EndHour { get; set; }
    
        public virtual Examination Examination { get; set; }
    }
}
