//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationsPaper
    {
        public ExaminationsPaper()
        {
            this.Actives = new HashSet<GroupRequest>();
            this.Receives = new HashSet<GroupRequest>();
            this.Groups = new HashSet<Group>();
            this.ParticipantVolunteers = new HashSet<ParticipantVolunteer>();
        }
    
        public int ExamPaperID { get; set; }
        public int CandidateID { get; set; }
        public int UniExamID { get; set; }
        public int VenueID { get; set; }
        public Nullable<int> CharityExamID { get; set; }
        public Nullable<int> LodgeRegisteredID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> ParticipantVolunteerID { get; set; }
        public Nullable<int> StatitonID { get; set; }
        public Nullable<int> PickUpTime { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Car Car { get; set; }
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual Group Group { get; set; }
        public virtual Lodge Lodge { get; set; }
        public virtual ParticipantVolunteer ParticipantVolunteer { get; set; }
        public virtual Room Room { get; set; }
        public virtual Station Station { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual UniversitiesExamination UniversitiesExamination { get; set; }
        public virtual ICollection<GroupRequest> Actives { get; set; }
        public virtual ICollection<GroupRequest> Receives { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<ParticipantVolunteer> ParticipantVolunteers { get; set; }
    }
}
