//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationsPaper
    {
        public ExaminationsPaper()
        {
            this.JoinsIns = new HashSet<JoinsIn>();
        }
    
        public int ExamPaperID { get; set; }
        public int CandidateID { get; set; }
        public int UniExamID { get; set; }
        public int VenueID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual UniversitiesExamination UniversitiesExamination { get; set; }
        public virtual ICollection<JoinsIn> JoinsIns { get; set; }
    }
}
