//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinsIn
    {
        public JoinsIn()
        {
            this.SchedulesCars = new HashSet<SchedulesCar>();
            this.SchedulesVolunteers = new HashSet<SchedulesVolunteer>();
        }
    
        public int JoinInID { get; set; }
        public int CharitiesExaminationsID { get; set; }
        public int ExamPaperID { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual ExaminationsPaper ExaminationsPaper { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<SchedulesCar> SchedulesCars { get; set; }
        public virtual ICollection<SchedulesVolunteer> SchedulesVolunteers { get; set; }
    }
}
