//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantVolunteer
    {
        public ParticipantVolunteer()
        {
            this.ExaminationsPapers = new HashSet<ExaminationsPaper>();
        }
    
        public int ParticipantVolunteerID { get; set; }
        public int VolunteerID { get; set; }
        public int CharityExamID { get; set; }
        public Nullable<int> ExamPaperID { get; set; }
        public string WayPoints { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ChairitiesExam ChairitiesExam { get; set; }
        public virtual ICollection<ExaminationsPaper> ExaminationsPapers { get; set; }
        public virtual ExaminationsPaper ExaminationsPaper { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
