//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulesCar
    {
        public int ScheduleCarID { get; set; }
        public int CarID { get; set; }
        public System.DateTime Day { get; set; }
        public System.DateTime ArriveTime { get; set; }
        public System.DateTime PickUpTime { get; set; }
        public string WayGo { get; set; }
        public string WayBack { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
