//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationCar
    {
        public StationCar()
        {
            this.ExaminationsPapers = new HashSet<ExaminationsPaper>();
        }
    
        public int StationCarIID { get; set; }
        public Nullable<int> CarID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ICollection<ExaminationsPaper> ExaminationsPapers { get; set; }
    }
}
